In [2]:
import pandas as pd
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [3]:
file_path = '/content/drive/My Drive/CIS550 Project/the_oscar_award.csv'
oscar=pd.read_csv(file_path)

Keep the awards for actor and actress only.

In [ ]:
oscar = oscar[oscar['category'].isin(['ACTOR','ACTRESS'])]

In [ ]:
oscar.dtypes

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
5308,1975,1976,48,ACTRESS,Isabelle Adjani,The Story of Adele H.,False
5309,1975,1976,48,ACTRESS,Ann-Margret,Tommy,False
5310,1975,1976,48,ACTRESS,Louise Fletcher,One Flew over the Cuckoo's Nest,True
5311,1975,1976,48,ACTRESS,Glenda Jackson,Hedda,False
5312,1975,1976,48,ACTRESS,Carol Kane,Hester Street,False

In [ ]:
oscar.groupby(['name','film']).size()

name            film
Adolphe Menjou  The Front Page                  1
Al Pacino       Dog Day Afternoon               1
                Serpico                         1
                The Godfather Part II           1
Alan Arkin      The Heart Is a Lonely Hunter    1
                                               ..
William Holden  Sunset Blvd.                    1
William Powell  Life with Father                1
                My Man Godfrey                  1
                The Thin Man                    1
Yul Brynner     The King and I                  1
Length: 468, dtype: int64