In [1]:
import pandas as pd
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

In [3]:
file_path = '/content/drive/My Drive/title.basics.tsv'
data_title_basics=pd.read_csv(file_path,sep='\t',na_values=['\\N'])
data_title_basics.shape

<ipython-input-3-bc3389a3487c>:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data_title_basics=pd.read_csv(file_path,sep='\t',na_values=['\\N'])

(9703451, 9)

1. Make a film of multiple genres into separate rows with one single genre.

In [4]:
data_title_basics1 = data_title_basics
data_title_basics1['genres'] = data_title_basics1['genres'].str.split(',')
data_title_basics1 = data_title_basics1.explode('genres')
data_title_basics1

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0.0,1894.0,NaN,1.0,Documentary
0,tt0000001,short,Carmencita,Carmencita,0.0,1894.0,NaN,1.0,Short
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0.0,1892.0,NaN,5.0,Animation
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0.0,1892.0,NaN,5.0,Short
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0.0,1892.0,NaN,4.0,Animation
...,...,...,...,...,...,...,...,...,...
9703448,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0.0,2010.0,NaN,NaN,Family
9703449,tt9916856,short,The Wind,The Wind,0.0,2015.0,NaN,27,Short
9703450,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0.0,2014.0,NaN,10,Adventure
9703450,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0.0,2014.0,NaN,10,Animation
9703450,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0.0,2014.0,NaN,10,Comedy

2. Convert the data type of startYear, endYear, runtimeMin to integer.

In [5]:
data_title_basics1[['startYear','endYear','runtimeMinutes']] = data_title_basics1[['startYear','endYear','runtimeMinutes']].apply(pd.to_numeric, errors='coerce').astype('Int32')

In [6]:
data_title_basics1.to_csv("title_basics.csv")